"use client"
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import SidebarDashboard from "@/components/sidebarDashboard";
import PrelineScript from "@/components/PrelineScript";
import {ThemeProvider} from "@/components/theme-provider";
import {ModeToggle} from "@/components/ui/mode-toogle";
import AdminPanelLayout from "@/components/admin-panel/admin-panel-layout";
import {ContentLayout} from "@/components/admin-panel/content-layout";
import {Breadcrumb} from "@/components/ui/breadcrumb";
import CustomBreadcrumb from "@/components/custom-breadcrumb";
import {usePathname, useRouter} from "next/navigation";
import {useEffect, useState} from "react";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//     title: "Webrana Itemku",
//     description: "Generated by create next app",
// };

export default function DashboardLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {

    const pathname = usePathname();
    const [pageTitle, setPageTitle] = useState<string>("Webrana"); // Default title

    function capitalizeFirstLetter(string) {
        return string.charAt(0).toUpperCase() + string.slice(1);
    }
    useEffect(() => {
        const pathSegments = pathname.split("/").filter(Boolean); // Split and filter path segments
        const lastPathSegment = pathSegments[pathSegments.length - 1]; // Get the last path segment

        setPageTitle(capitalizeFirstLetter(lastPathSegment))
    }, [pathname]);
    return (
        <AdminPanelLayout>
            <ContentLayout title={pageTitle}>
                <CustomBreadcrumb/>
                {children}
            </ContentLayout>
        </AdminPanelLayout>
    );
}
